---
- name: Configurar e instalar servidor web Apache
  hosts: webservers
  become: yes
  vars_files:
    - group_vars/webservers.yml
  roles:
    - apache2

- name: Configurar copias de seguridad automáticas
  hosts: webservers
  become: yes
  vars_files:
    - group_vars/webservers.yml
  roles:
    - backup
